ioBroker/ioBroker.discovery

- README.md
- lib/adapters/fronius.js
- lib/adapters/rflink.js
> add fronius

- .gitignore
- lib/adapters/landroid.js
Bei der Eingabe der PIN bin ich mir nicht sicher ob es so ok ist, aber vom Prinzip her sollte es so gehen. Ich teste es am Wochenende das Ganze mal.
> (ldittmar) discovery landroid mower

- lib/adapters/squeezebox.js
Simple adapter discovery using raw TCP port 9090.
Any feedback is appreciated!
> Added squeezebox adapter support

- lib/adapters/musiccast.js
> initial for comments and testing

- lib/adapters/loxone.js
**Important:** add this only into a new version of ioBroker.discovery once my pull requests for ioBroker.repository were merged back, otherwise the adapter can't be found.
> Added loxone adapter support.

- lib/adapters/homepilot
Automated discovery integrated
Pix
> Added Rademacher Homepilot detection

- lib/adapters/epson_stylus_px830
- lib/adapters/homepilot.js
> epson_stylus_px830 detection

- lib/adapters/energymanager.js
added pattern for energymanager
> added pattern for energymanager

- README.md
> added energymanager in readme

- io-package.json
- package.json
Don't know, if it's my turn to raise the version because of the new pattern for the energymanager.
> version raised to 1.2.2, new pattern energymanager

- lib/adapters/energymanager.js
changed the keyword solarwatt to the even bigger provider kiwigrid which includes solarwatt, eon and more.
> changed solarwatt pattern to kiwigrid

- lib/adapters/stiebel-isg.js
pattern for the new stiebel-isg adapter (Stiebel-Eltron/Tecalor Internet Service Gateway for Heatpumps)
> discovery-pattern for stiebel-isg adapter

- README.md
- lib/adapters/denon.js
- lib/adapters/g-homa.js
- lib/adapters/harmony.js
- lib/adapters/sonnen.js
- lib/methods/mdns.js
-closes https://github.com/Pmant/ioBroker.harmony/issues/15
-remove unneeded debug logging of my sonnen adapter
-minor changes
-readme update
> added detection for harmony hub/fakeroku

- lib/adapters/broadlink2.js
Added also some new devices to the list of supported ones and the rename/delete of the file
> broadlink discovery for broadlink2

- README.md
- lib/adapters/bshb.js
I am not 100% sure if this is working. Is it true that this only works if a stable version of the adapter is available? I got error messages because discovery complained that bshb adapter not found. I also created pr for stable version of bshb.
> * (holomekc) detect Bosch Smart Home Controller

- lib/adapters/solarlog.js
detection of Solar-Log devices
> include solarlog.js

- README.md
- lib/adapters/squeezeboxrpc.js
as a preperation to go to the stable repository
i shameless copied the squeezebox.js discovery code and changed squeezebox to squeezeboxrpc :)
> add SqueezeboxRPC to discovery

- lib/adapters/bshb.js
Prevent issue mentioned in: [issue 14](https://github.com/holomekc/ioBroker.bshb/issues/14)
> * (holomekc) replace silly log with debug

- README.md
- lib/adapters/mydlink.js
- lib/methods/mdns.js
mydlink devices can be detected by mdns. (Though not 100% in discovery adapter, works about 50% of my tries. Why is "broadcast" disabled?).
Will already ask for pin of devices and configure adapter completely.
> add mydlink adapter to discovery

- lib/adapters/heos.js
GitHub: https://github.com/withstu/ioBroker.heos
Forum: https://forum.iobroker.net/topic/10420/vorlage-denon-heos-script
> add heos adapter

- lib/adapters/heos.js
password encryption is currently not supported by discovery adapter
> remove heos username/password input

- .npmignore
- lib/adapters/valloxmv.js
- lib/methods/upnp.js
Add Upnp Multicast listener
Add ValloxMV discovery
Add .dev-server
> Add ValloxMV discovery

- README.md
- lib/adapters/e3dc-rscp.js
Uses UPnP discovery to detect E3/DC devices supporting RSCP.
> Add e3dc-rscp

- README.md
- lib/adapters/myvbus.js
- lib/adapters/resol.js
- lib/methods/vbus.js
The myvbus.js detector requires the vbus.js method. However, discovery of other vbus adapters like ioBroker.resol could easily be implemented based on the vbus.js method.
> Add: myvbus.js detector & vbus.js method
